services:
  app:
    environment:
      VIRTUAL_HOST: ${PUBLIC_DOMAIN}
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: ${PUBLIC_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}

  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.7
    container_name: ppt-leaderboard-nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  letsencrypt:
    image: nginxproxy/acme-companion:2.6
    container_name: ppt-leaderboard-letsencrypt
    depends_on:
      - nginx-proxy
    environment:
      NGINX_PROXY_CONTAINER: ppt-leaderboard-nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  certs:
  vhost:
  html:
  acme:
